\documentclass[a4paper]{article}

\title{Structural Change}
\author{Diego Valle-Jones}

\usepackage{longtable}
\usepackage{anysize}

\marginsize{1cm}{1cm}{2cm}{2cm}
\begin{document}

\maketitle

The R package strucchange was used to test for stability in the linear
regressions of the homicide rates to see if the different military
operations caused it to increase.

\begin{verbatim}
breakpoints(rate ~ 1 + ndays)
\end{verbatim}

where rate is the homicide rate, and ndays are the number of days in the month

In the tables below, lower refers to the lower confidence interval, and
upper refers to the upper confidence interval

<<results=tex, echo=FALSE>>=
setwd("timelines/report")
sanitizeCol <- function(x){
  x <- gsub("^Joint Operation", "J. O.", x)
  x <- gsub("^Operation", "O.", x)
  x
}
printTable <- function(df){
  print(xtable(df), include.rownames = FALSE,
        tabular.environment = "longtable",
        floating = FALSE,
        sanitize.colnames.function = sanitizeCol)
}
@

\section{Michoacan}

<<results=tex,echo=FALSE>>=
printTable(report.ll$bcn)
@

\begin{figure}
\begin{center}
<<label=fig1,fig=TRUE,echo=FALSE>>=
print(createPlot(mich.df, ll.mich, "Michoacan"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:one}
\end{figure}


\section{Guerrero}

From the charts it looks as if there were two breaks in the homicide rate,
the first one coinciding with the arrival of the army, when there was
a decrease in the homicide rate, especially in Acapulco. And a second
one when Alfredo Beltran Leyva was captured by the army.

<<results=tex,echo=FALSE>>=
printTable(report.ll$gue)
@

\begin{figure}
\begin{center}
<<label=fig2,fig=TRUE,echo=FALSE>>=
print(createPlot(gue.df, ll.gue, "Guerrero"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:two}
\end{figure}



\section{Baja California}
I set the minimum segment size as three because the capture of Eduardo
Arrellano Felix occurred near the end of the year, so not many months
with a high number of homicides were available for testing.

<<results=tex,echo=FALSE>>=
printTable(report.ll$bcn)
@

\begin{figure}
\begin{center}
<<label=fig3,fig=TRUE,echo=FALSE>>=
print(createPlot(bcn.df, ll.bcn, "Baja California"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:three}
\end{figure}


\section{Durango}

<<results=tex,echo=FALSE>>=
printTable(report.ll$dur)
@

\begin{figure}
\begin{center}
<<label=fig4,fig=TRUE,echo=FALSE>>=
print(createPlot(dur.df, ll.dur, "Durango"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:four}
\end{figure}


\section{Sonora}

<<results=tex,echo=FALSE>>=
printTable(report.ll$son)
@

\begin{figure}
\begin{center}
<<label=fig5,fig=TRUE,echo=FALSE>>=
print(createPlot(son.df, ll.son, "Sonora"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:five}
\end{figure}


\section{Sinaloa}

<<results=tex,echo=FALSE>>=
printTable(report.ll$sin)
@

\begin{figure}
\begin{center}
<<label=fig6,fig=TRUE,echo=FALSE>>=
print(createPlot(sin.df, ll.sin, "Sinaloa"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:six}
\end{figure}


\section{Tamaulipas}

From the charts it looks like there were 2 breaks in the homicide
rate, one corresponding to when ``El Chapo'' sent ``La barbie'' to take
over the plaza in Nuevo Leon, and the other to when he realized he
wasn't going to be able to take it over. Notice how the violence
decreased about 5 months before the army arrived.

<<results=tex,echo=FALSE>>=
printTable(report.ll$tam)
@

\begin{figure}
\begin{center}
<<label=fig7,fig=TRUE,echo=FALSE>>=
print(createPlot(tam.df, ll.tam, "Tamaulipas"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:seven}
\end{figure}


\section{Nuevo Leon}

<<results=tex,echo=FALSE>>=
printTable(report.ll$nl)
@

\begin{figure}
\begin{center}
<<label=fig8,fig=TRUE,echo=FALSE>>=
print(createPlot(nl.df, ll.nl, "Nuevo Leon"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:eight}
\end{figure}

\section{Chihuahua}

<<results=tex,echo=FALSE>>=
printTable(report.ll$chi)
@

\begin{figure}
\begin{center}
<<label=fig9,fig=TRUE,echo=FALSE>>=
print(createPlot(chi.df, ll.chi, "Chihuahua"))
@
\end{center}
\caption{Homicide rates in municipalities with more than
  100,000 people}
\label{fig:nine}
\end{figure}



\end{document}
<<echo=FALSE>>=
setwd("../..")
@