\documentclass[a4paper]{article}

\title{Structural Change in Homicide Rates}
\author{Diego Valle-Jones}

\usepackage{longtable}
\usepackage{anysize}

\marginsize{1cm}{1cm}{2cm}{2cm}
\begin{document}

\maketitle

The R package strucchange was used to test for stability in the linear
regressions of the homicide rates to see if the different military
operations caused it to increase.

\begin{verbatim}
breakpoints(rate ~ ndays)
\end{verbatim}

where rate is the homicide rate, and ndays are the number of days in each month

In the tables below, lower refers to the lower confidence interval, and
upper refers to the upper confidence interval

<<results=tex, echo=FALSE>>=
setwd("timelines/report")
sanitizeCol <- function(x){
  x <- gsub("^Joint Operation", "J. O.", x)
  x <- gsub("^Operation", "O.", x)
  x
}
printTable <- function(df){
  df.table <- xtable(df)
  print(xtable(df.table), include.rownames = FALSE,
        tabular.environment = "longtable",
        floating = FALSE,
        sanitize.colnames.function = sanitizeCol)
}
@

\section{Michoacan}

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$mich)
@

The cluster of municipalities near the Pacific Coast and the Tierra
Caliente that have a very high homicide rate:

<<results=tex,echo=FALSE>>=
printTable(report.ll$mich.int)
@


\section{Guerrero}

From the charts it looks as if there were two breaks in the homicide rate,
the first one coinciding with the arrival of the army, when there was
a decrease in the homicide rate, especially in Acapulco. And a second
one when Alfredo Beltran Leyva was captured by the army.

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$gue)
@

These are the municipalities bordering Michoacan:

<<results=tex,echo=FALSE>>=
printTable(report.ll$gue.int)
@




\section{Baja California}
I set the minimum segment size as three because the capture of Eduardo
Arrellano Felix occurred near the end of the year, so not many months
with a high number of homicides were available for testing.

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$bcn)
@


\section{Durango}

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$dur)
@

These are the municpalities with a high homicide rate:
<<results=tex,echo=FALSE>>=
printTable(report.ll$dur.int)
@


\section{Sonora}

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$son)
@


\section{Sinaloa}

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$sin)
@

Municipalities with a high homicide rate:

<<results=tex,echo=FALSE>>=
printTable(report.ll$sin.int)
@



\section{Tamaulipas}

From the charts it looks like there were 2 breaks in the homicide
rate, one corresponding to when ``El Chapo'' sent ``La Barbie'' to take
over the plaza in Nuevo Laredo, and the other to when he realized he
wasn't going to be able to take it over. 

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$tam)
@



\section{Nuevo Leon}

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$nl)
@


\section{Chihuahua}

Municipalities with more than a 100,000 thousand people:

<<results=tex,echo=FALSE>>=
printTable(report.ll$chi)
@

These are the municpalities near the US border:
<<results=tex,echo=FALSE>>=
printTable(report.ll$chi.bdr)
@

These are the municipalities with a very high homicide rate:

<<results=tex,echo=FALSE>>=
printTable(report.ll$chi.int)
@



\end{document}
<<echo=FALSE>>=
setwd("../..")
@
